stages:
  - build
  - push

build:5.6:
  stage: build
  script:
    - ./build 5.6

build:7.0:
  stage: build
  script:
    - ./build 7.0

build:7.1:
  stage: build
  script:
    - ./build 7.1

build:7.2:
  stage: build
  script:
    - ./build 7.2

build:7.3:
  stage: build
  script:
    - ./build 7.3

build:7.4:
  stage: build
  script:
    - ./build 7.4

build:8.0:
  stage: build
  script:
    - ./build 80
