stages:
  - build

variables:
  DOCKER_REGISTRY: index.docker.io

.build:
  stage: build
  script:
    - ./build ${PHP_VERSION}
    - "docker login --username ${ACCESS_TOKEN_USER} --password ${ACCESS_TOKEN}"
    - "docker push ${DOCKER_REGISTRY}/marmaladegmbh/php:${PHP_VERSION}"

build:5.6:
  extends: .build
  variables:
    PHP_VERSION: "5.6"

build:7.0:
  extends: .build
  variables:
    PHP_VERSION: "7.0"

build:7.1:
  extends: .build
  variables:
    PHP_VERSION: "7.1"

build:7.2:
  extends: .build
  variables:
    PHP_VERSION: "7.2"

build:7.3:
  extends: .build
  variables:
    PHP_VERSION: "7.3"

build:7.4:
  extends: .build
  variables:
    PHP_VERSION: "7.4"

build:8.0:
  extends: .build
  variables:
    PHP_VERSION: "8.0"
