FROM    php:7.3-fpm-alpine3.9

ARG     NODEJS_DISABLE=

# https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Configuration_Directives

ENV     WEB_ROOT=/app

RUN     apk add --no-cache bash

COPY    apache2-foreground-user install-php /usr/local/bin/

RUN     /usr/local/bin/install-php && rm /usr/local/bin/install-php

WORKDIR /app

CMD     ["apache2-foreground-user"]

# VOLUME /app/data
