FROM    php:8.0-apache

ARG     NODEJS_DISABLE=1

# https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Configuration_Directives

ENV     WEB_ROOT=/app \
        WEB_PORT=80 \
        COMPOSER_CACHE_DIR=/dev/null \
        COMPOSER_ALLOW_SUPERUSER=1 \
        COMPOSER_NO_INTERACTION=1


COPY    apache2-foreground-user install-php /usr/local/bin/

COPY    ./xhgui/ /xhgui/

RUN     /usr/local/bin/install-php && rm /usr/local/bin/install-php

WORKDIR /app

ENTRYPOINT ["/usr/bin/dumb-init","--rewrite","28:0", "--"]

CMD     ["apache2-foreground-user"]

# VOLUME /app/data
