FROM    php:8.1-apache

ARG     NODEJS_DISABLE=1

RUN sed -Ei 's@^mozilla/DST_Root_CA_X3.crt$@!mozilla/DST_Root_CA_X3.crt@g' /etc/ca-certificates.conf && \
    update-ca-certificates

# https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Configuration_Directives

ENV     WEB_ROOT=/app \
        WEB_PORT=80 \
        COMPOSER_CACHE_DIR=/dev/null \
        COMPOSER_ALLOW_SUPERUSER=1 \
        COMPOSER_NO_INTERACTION=1


COPY    apache2-foreground-user install-php /usr/local/bin/

RUN     /usr/local/bin/install-php && rm /usr/local/bin/install-php

WORKDIR /app

ENTRYPOINT ["/usr/bin/dumb-init","--rewrite","28:0", "--"]

CMD     ["apache2-foreground-user"]

# VOLUME /app/data
