FROM    php:7.1-apache

ARG     NODEJS_DISABLE=

# https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Configuration_Directives

ENV     WARNING="Warning: This PHP version is not maintained anymore! Message to data security officer has been sent."

ENV     WEB_ROOT=/app \
        WEB_PORT=80 \
        COMPOSER_CACHE_DIR=/dev/null \
        COMPOSER_ALLOW_SUPERUSER=1 \
        COMPOSER_NO_INTERACTION=1

COPY    apache2-foreground-user install-php /usr/local/bin/

RUN     /usr/local/bin/install-php && rm /usr/local/bin/install-php

WORKDIR /app

ENTRYPOINT ["/usr/bin/dumb-init","--rewrite","28:0", "--"]

CMD     ["apache2-foreground-user"]

# VOLUME /app/data
