#!/bin/bash
set -e

if [ ! -z "$PHP_MAIL_FROM" ]; then
	sed -i "s/john.doe@example.com/${PHP_MAIL_FROM}/" /usr/local/etc/php/conf.d/sendmail.ini
fi

if [ ! -z "$PHP_MAIL_HOST" ]; then
	sed -i "s/--host=mail/--host=${PHP_MAIL_HOST}/" /usr/local/etc/php/conf.d/sendmail.ini
fi

rm -rf /app/data/temp/sally/yaml-cache/*
rm -rf /app/data/temp/sally/less-cache/*
mkdir -p /app/data/upload_tmp
mkdir -p /app/data/session


if [ ! -z "$WWW_DATA_UID" ]; then
	echo "www-data uid => ${WWW_DATA_UID}"
	usermod -u ${WWW_DATA_UID} www-data
	if [ ! -z "$WWW_DATA_GID" ]; then
		echo "www-data gid => ${WWW_DATA_GID}"
		groupmod -g ${WWW_DATA_GID} www-data
	fi
	chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2
fi

chown -R www-data:www-data /app/data

if [ ! -z "$ROBOTS_DISALLOW" ]; then
	echo "User-agent: *" > $WEB_ROOT/robots.txt
	echo "Disallow: $ROBOTS_DISALLOW" >> $WEB_ROOT/robots.txt
fi

if [ ! -z "$PHP_TYPO3_INI" ]; then
	echo "always_populate_raw_post_data=-1" > /usr/local/etc/php/conf.d/typo3.ini
	echo "max_input_vars=1500" >> /usr/local/etc/php/conf.d/typo3.ini
	echo "max_execution_time=240" >> /usr/local/etc/php/conf.d/typo3.ini
fi

exec /usr/local/bin/apache2-foreground
