name: build

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php:
          [
            5.6,
            5.6-backport,
            7.0,
            7.1,
            7.1-fpm-alpine,
            7.2,
            7.2-fpm-alpine,
            7.3,
            7.3-fpm-alpine,
            7.4,
            7.4-fpm-alpine,
            8.0,
            8.1,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: marmaladegmbh/php,ghcr.io/marmaladede/php
          tags: |
            type=semver,pattern=${{ matrix.php }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "{context}/Dockerfile-${{ matrix.php }}"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
